title: Ann's Site
description: Site built with GitHub pages.
show_downloads: true
theme: jekyll-theme-cayman

# Social Media

twitter_username: Bioinfodotca
github_username:  bioinformatics-ca

# Build settings
markdown: kramdown

# Google Services

google_analytics:
